#!/bin/bash

## WORKAROUND JUSTIFICATION: Needed for now as I can't seem to
##    figure out how to run 'exec' under sudo but changing to 
##    other user


## make sure 'vagrant' role still DOES NOT exist yet...
user_exist=$(psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='vagrant'")
if [[ "$user_exist" = "" ]]; then
  sudo -u postgres /usr/bin/createuser vagrant --createdb -s

  ## send proper exit code '0' if above line is successful
  ## needed so as NOT TO FAIL 'puppet'
  [[ $? -eq 0 ]] && end_retval=0
elif [[ "$user_exist" = "1" ]]; then
  ## DO NOT SEND other code to 'puppet' just because role already exist.
  ## Let it be done by other error...
  end_retval=0
fi

exit $end_retval
